local tokyo_night = {
   black          = '#15161E',
   red            = '#F7768E',
   green          = '#9ECE6A',
   yellow         = '#E0AF68',
   blue           = '#7AA2F7',
   magenta        = '#BB9AF7',
   cyan           = '#7DCFFF',
   white          = '#A9B1D6',
   bright_black   = '#414868',
   bright_red     = '#F7768E',
   bright_green   = '#9ECE6A',
   bright_yellow  = '#E0AF68',
   bright_blue    = '#7AA2F7',
   bright_magenta = '#BB9AF7',
   bright_cyan    = '#7DCFFF',
   bright_white   = '#C0CAF5',
   comment        = '#565F89',
   bg_dark        = '#1A1B26',
   bg             = '#24283B',
   bg_light       = '#3B4261',
   fg             = '#C0CAF5',
   fg_dark        = '#A9B1D6',
   accent         = '#7AA2F7',
   selection_bg   = '#33467C',
   selection_fg   = '#C0CAF5',
   cursor_bg      = '#C0CAF5',
   cursor_border  = '#C0CAF5',
   cursor_fg      = '#1A1B26',
}

local colorscheme = {
   foreground = tokyo_night.fg,
   background = tokyo_night.bg,
   cursor_bg = tokyo_night.cursor_bg,
   cursor_border = tokyo_night.cursor_border,
   cursor_fg = tokyo_night.cursor_fg,
   selection_bg = tokyo_night.selection_bg,
   selection_fg = tokyo_night.selection_fg,
   ansi = {
      tokyo_night.black,
      tokyo_night.red,
      tokyo_night.green,
      tokyo_night.yellow,
      tokyo_night.blue,
      tokyo_night.magenta,
      tokyo_night.cyan,
      tokyo_night.white,
   },
   brights = {
      tokyo_night.bright_black,
      tokyo_night.bright_red,
      tokyo_night.bright_green,
      tokyo_night.bright_yellow,
      tokyo_night.bright_blue,
      tokyo_night.bright_magenta,
      tokyo_night.bright_cyan,
      tokyo_night.bright_white,
   },
   tab_bar = {
      background = tokyo_night.bg_dark,
      active_tab = {
         bg_color = tokyo_night.bg_light,
         fg_color = tokyo_night.fg,
      },
      inactive_tab = {
         bg_color = tokyo_night.bg,
         fg_color = tokyo_night.comment,
      },
      inactive_tab_hover = {
         bg_color = tokyo_night.bg_light,
         fg_color = tokyo_night.fg_dark,
      },
      new_tab = {
         bg_color = tokyo_night.bg,
         fg_color = tokyo_night.comment,
      },
      new_tab_hover = {
         bg_color = tokyo_night.bg_light,
         fg_color = tokyo_night.fg_dark,
         italic = true,
      },
   },
   visual_bell = tokyo_night.red,
   indexed = {
      [16] = tokyo_night.yellow,
      [17] = tokyo_night.red,
   },
   scrollbar_thumb = tokyo_night.comment,
   split = tokyo_night.comment,
   compose_cursor = tokyo_night.magenta,
}

return colorscheme
